#define fLUT_TechniqueName Urban_Cinematic_LUT
#define fLUT_LutList " FOREST918-DARK-ROMAN-HENSE\0 FOREST918-LIGHT-ROMAN-HENSE\0 URBAN918-DARK-S-LOG3-ROMAN-HENSE\0 URBAN918-LIGHT-S-LOG3-ROMAN-HENSE\0 URBANBLUES-DARK-S-LOG3-ROMAN-HENSE\0 URBANBLUES-LIGHT-S-LOG3-ROMAN-HENSE\0 "
#define fLUT_TextureName "Urban Cinematic LUT.png"
#define fLUT_TileSizeXY 64
#define fLUT_TileAmount 64
#define fLUT_LutAmount 6
#include "_BaseLUT.fxh"
